### PR TITLE
fix: remove UIO text-size preference

### PR DESCRIPTION
**Pull request by BlueSlug**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run start` and reviewing affected routes
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

This update will remove the UIO text-size preference in an attempt to address #57 in the short term. This was one of the solutions suggested when the issue was originally filed, as it's the approached used in the [WeCount website](https://wecount.inclusivedesign.ca/) which encountered similar issues.

Issue #57 should remain open after merging this PR, since the issue will not have been dealt with in what I consider a proper manner. This solution is not intended to be in place in the long term.

## Steps to test

1. Click on "+ show preferences"

**Expected behavior:** The "text size" preference should not be in the list of panels

## Additional information

N/A

## Related issues

Is a partial solution to #57 but does not solve the problem and therefore **_does not_** resolve the issue.

### CODE REVIEW

**Comment by cindyli** [comment]
This pull request looks good to me.

@greatislander, can you have a look as this PR bases off and modifies the code from the `eleventy-plugin-fluid` dependency? Thanks.

**Comment by BlueSlug** [comment]
> This looks great! My only suggestion is that you name the shortcode something like `uioCustomInit`, for the following reasons:
> 
> 1. This makes it clear that the shortcode is used to initialize UIO like the one it's based on.
> 2. Eleventy Nunjucks shortcodes seem to use the convention of camelCase for naming and I think it's probably good to stick to that for consistency.

Thanks for the suggestion! In fact it's nearly the same name as I'd first chosen (`uioInitCustom`), but for some reason I just couldn't get it to work (more on this in a moment :)), so I switched to `customUIO` in an attempt to circumvent any strange caching I couldn't explain. Turns out it was the duplication of the UIO shortcode call between `base.njk` and `home.njk`. We'll have to DRY those out at some point.

I wasn't sure about the naming style, so it's good to know that head-down camel-case is the way to go. I'd used snake-case since that's what `svg_sprite` used. Do you recommend renaming all three shortcodes to use camel-case? (ditto for `svg_sprite` in Trivet?)

**Comment by greatislander** [comment]
> I wasn't sure about the naming style, so it's good to know that head-down camel-case is the way to go. I'd used snake-case since that's what `svg_sprite` used. Do you recommend renaming all three shortcodes to use camel-case? (ditto for `svg_sprite` in Trivet?)

Wouldn't be a bad idea. I don't know where `svg_sprite` originated as it's not in Trivet :)

**Review by greatislander — APPROVED** [review]
This looks great, if you opt to rename other shortcodes that could happen in a separate PR.

**Comment by BlueSlug** [comment]
> > I wasn't sure about the naming style, so it's good to know that head-down camel-case is the way to go. I'd used snake-case since that's what `svg_sprite` used. Do you recommend renaming all three shortcodes to use camel-case? (ditto for `svg_sprite` in Trivet?)
> 
> Wouldn't be a bad idea. I don't know where `svg_sprite` originated as it's not in Trivet :)

Oh sure enough! I'd pulled it from the Floe Project site, actually, so I'll make the change there :)

**Pull request merged**
