### PR TITLE
fix: update footer styling to better match design

### LINKED ISSUE #60: Update footer styling to match designs
Update the page footer styling (both narrow- and wide-screen layouts) to more closely match the design.

Specifically, the logos at the bottom and the maximum width of the footer (spec is 90rem), as well as confirming the typesetting and focus/hover styles are as designed.

image

image

### PR DESCRIPTION
**Pull request by BlueSlug**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run start` and reviewing affected routes
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

This update will revise styling rules for the footer to better match the design, and in the process solve some CSS bugs and scaling issues.

## Steps to test

1. Scroll down to the footer of the page
2. Resize the window or view it on multiple devices

**Expected behavior:** The footer should scale responsively without any CSS errors.

## Additional information

N/A

## Related issues

Resolves #60

### CODE REVIEW

**Comment by cindyli** [comment]
Logos wrap into two lines if you gradually make the screen smaller or increase the font size:
Screen Shot 2022-04-26 at 9 47 18 AM

**Comment by cindyli** [comment]
I don't find the mobile design for the footer in [the figma](https://www.figma.com/file/JVjWAROz9jZBbDaemwom2y/ILDH?node-id=0%3A1).

cc @carenwatkins

**Comment by BlueSlug** [comment]
> Logos wrap into two lines if you gradually make the screen smaller or increase the font size: Screen Shot 2022-04-26 at 9 47 18 AM

This is behaving as I intended it to. The mobile design shows two rows with two logos each, and the Desktop design shows a single row, so this was my attempt at a responsive transition between the two. It didn't feel right jumping from a row of four to two rows of two, and things got weird at narrower widths.

I can look into this if you feel it's awkward. Maybe by setting up some media queries that could work well in various resolutions, font sizes and UIO settings combos..

---

> I don't find the mobile design for the footer in [the figma](https://www.figma.com/file/JVjWAROz9jZBbDaemwom2y/ILDH?node-id=0%3A1).
> 
> cc @carenwatkins

The mobile designs are on the "Mobile" page listed in the top-left of Figma. If you don't see the toolbars, the shortcut on Windows is ctrl+\ so I would guess try command+\. The footer design can be found at the bottom of the leftmost page design

image

**Comment by cindyli** [comment]
> The mobile designs are on the "Mobile" page listed in the top-left of Figma.
Thanks for pointing out. I missed this tab. :)

> This is behaving as I intended it to. The mobile design shows two rows with two logos each, and the Desktop design shows a single row, so this was my attempt at a responsive transition between the two. It didn't feel right jumping from a row of four to two rows of two, and things got weird at narrower widths.

It's great to see how logos should look like on the mobile design. I personal like the idea of the gradual transition. One issue with it is, on my screen where the default font size is larger, logos ended up in three lines on the iphone 5 screen:

Screen Shot 2022-04-26 at 10 27 48 AM

@carenwatkins' input will be helpful.

**Comment by BlueSlug** [comment]
I actually found the 1-2-1 pattern in your screenshot aesthetically pleasing :) but it is definitely a subjective matter and I agree that some design input would be quite helpful

**Comment by cindyli** [comment]
The new logo arrangement looks and works great.

In terms of whether indicates different sections, since the common design with other sites is not to, it may not be necessary to wait for @carenwatkins' feedback. I will merge this pull request. If the decision is to add the separator, it can be addressed in another ticket.

Thanks for the nice work, @BlueSlug.

**Review by cindyli — APPROVED** [review]

**Pull request merged**
