### PR TITLE
feat: add audio-tactile cards and new article

### LINKED ISSUE #74: Add audio-tactile cards
## Description of the work

Add a new page to introduce and describe 3D-printed audio-tactile graphics to the ILDH, as well as another new page with a list of 45 "cards" with recommendations for designing audio-tactile artefacts. This list page will include new accordion-style controls to list the cards themselves within their categories. Consideration should be paid to the two styles of accordion already present within the site (the _Article Contents_ for article pages and root page sections).

The designs and content for these two new pages can be found here (disregard the "EPUB 3" designs for this work): https://www.figma.com/file/jcUv3IqUILArTF8yKdCUK1/Recommendations-page?node-id=0%3A1

## The plan so far

- [x] Add the new article
- [x] Add a template for the new cards page
- [x] Add a Sass file for the new cards page
- [x] Add a new collection or directory within the Techniques collection to contain the recommendation card Markdown files
- [x] Add a template for a single card, using frontmatter to split the card "intro" content from its expanded content
- [x] Add/alter accordion controls to organize the cards within their respective sections
- [x] Test the site

## Screenshots

Intro page
image

Recommendation cards
image

### PR DESCRIPTION
**Pull request by BlueSlug**
* [x] This pull request has been linted by running `npm run lint` without errors
* [x] This pull request has been tested by running `npm run start` and reviewing affected routes
* [x] This pull request has been built by running `npm run build` without errors
* [x] This isn't a duplicate of an existing pull request

## Description

This update adds a new page comprised of 45 recommendation cards for audio-tactile design, as well as a new article introducing this new page.

The designs for the new page and article can be found here: https://www.figma.com/file/jcUv3IqUILArTF8yKdCUK1/Recommendations-page?node-id=0%3A1

## Steps to test

1. Go to the Techniques page
2. Expand the _Authoring Content_ and click on _3D Printed Audio-Tactile Graphics_
3. Click on either "a set of recommendations" or "the 45 recommendations" links to open the cards page
4. Click on "Code Legend" to expand the code legend
5. Click on the "expand all" button
6. Click on the "collapse all" button
7. Click on "Materials and Production"
8. Click on "General"
9. Click on the MPG.3 card

**Expected behavior:** The sections, subsections and cards should all expand and collapse when the expand & collapse all buttons are activated (except those cards without any content to expand: _PG.3_, _PAT.3_, and _CUI.7_). After steps 7 through 9, the _MPG.3_ card should also be expanded. Other cards should expand and collapse likewise, except those cards which do not have an icon since they don't have any additional information

## Additional information

Some interactions or design elements are not implemented exactly as designed for various practical reasons.

## Related issues

Resolves #74

### CODE REVIEW

**Comment by cindyli** [comment]
When the link focus style is applied, its yellow background and border overlaps contents in lines before and after the link. Reducing the padding of the focus/hover style should fix the issue. Please double check if the fix is still compatible with the design. Thanks.

Screen Shot 2022-08-08 at 5 50 35 PM

**Comment by cindyli** [comment]
When using screen reader landing on PG.3 kind of cards that don't have expanded information, the screen reader announces it's a button. But clicking on it doesn't do anything, which is a bit confusing. However, if we use <div> for this kind of cards, they would be inconsistent with other cards. Maybe designers have ideas.

**Comment by BlueSlug** [comment]
> When using screen reader landing on PG.3 kind of cards that don't have expanded information, the screen reader announces it's a button. But clicking on it doesn't do anything, which is a bit confusing. However, if we use
> 
> for this kind of cards, they would be inconsistent with other cards. Maybe designers have ideas.

Good catch! I also gave this some thought before marking the PR ready but didn't have a solution in mind at that point. An idea I had last night was to change them to a different element from `button`, perhaps `article` is the semantic element that makes the most sense, and then apply the `button` role for those that do expand and not provide it for those that don't.

What do you think? It is inconsistent, as you mentioned, though perhaps this is acceptable, or at least more acceptable than a button that doesn't do anything and doesn't announce anything to ATs when activated.

**Comment by BlueSlug** [comment]
@cindyli ready for more review :)

**Comment by cindyli** [comment]
Thanks for the fix, @BlueSlug. They look great. One issue with the card element is, if you tab land on a card element, using "enter" key no longer expand/collapse the card content, which is incorrect. Mouse clicks still work fine. It's probably because the change from <button> from <article> removes the natural behavior of accepting "enter" action with buttons.

**Comment by BlueSlug** [comment]
@cindyli ready for review

I've added keybindings on `keydown` for "space" and "enter" which work properly in several environments

**Pull request merged**
